version: '2'

services:
  app:
    image: schmunk42/yii2-app-basic
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=books
      - MYSQL_USER=books
      - MYSQL_PASSWORD=secret
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
